# Generated by Django 3.1.6 on 2023-05-09 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='produit',
        ),
        migrations.AddField(
            model_name='produits',
            name='categorie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Produits_Categories', to='products.categories'),
        ),
        migrations.AddField(
            model_name='produits',
            name='promotions',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Produits_Promotions', to='products.promotions'),
        ),
    ]
