# Generated by Django 3.1.6 on 2023-05-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230509_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Libelle',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
