# Generated by Django 4.2.1 on 2023-05-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tests_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
