# Generated by Django 3.1.6 on 2023-05-09 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230509_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='categorie',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Produits_Categories', to='products.categories'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='promotions',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Produits_Promotions', to='products.promotions'),
        ),
    ]
