# Generated by Django 3.1.6 on 2023-05-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230509_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='Libelle',
            new_name='libelle',
        ),
    ]
