# Generated by Django 3.1.6 on 2023-05-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_admin_product',
            field=models.BooleanField(default=False),
        ),
    ]
