# Generated by Django 3.1.6 on 2023-05-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersaccount2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersAccount2',
        ),
    ]
